apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: master
  namespace: default
  annotations:
    # TODO: Temporary CORS config for frontend development. Allowing http://localhost:3000.
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Accept, Authorization, Content-Type, Origin, X-Requested-With"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  rules:
# TODO: We have disabled the host for now
{{/*    - host: test.axile.nucleon-forge.com*/}}
    - http:
        paths:
          - backend:
              service:
                name: master
                port:
                  number: 8080
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: front-end
                port:
                  number: 8080
            path: /
            pathType: Prefix
