package com.axelixlabs.axelix.sbs.spring.core.transactions

import java.sql.Connection
import java.sql.PreparedStatement

/**
 * A {@link Connection} wrapper that replaces {@link PreparedStatement} instances
 * with proxies collecting query execution statistics.
 *
 * @author Sergey Cherkasov
 */
class ProxyingConnection(private val delegate : Connection, private val statsCollector : QueriesStatsCollector) : Connection by delegate {

    override fun prepareStatement(sql: String): PreparedStatement {
        return recordStats(sql) {
            delegate.prepareStatement(sql)
        }
    }

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement {
        return recordStats(sql) {
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency)
        }
    }

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int
    ): PreparedStatement {
        return recordStats(sql) {
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability)
        }
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement {
        return recordStats(sql) {
            delegate.prepareStatement(sql, autoGeneratedKeys)
        }
    }

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement {
        return recordStats(sql) {
            delegate.prepareStatement(sql, columnIndexes)
        }
    }

    override fun prepareStatement(sql: String, columnNames: Array<String>): PreparedStatement {
        return recordStats(sql) {
            delegate.prepareStatement(sql, columnNames)
        }
    }

    private fun recordStats(sql: String, supplier: () -> PreparedStatement): PreparedStatement {
        val startTimeNano: Long = System.nanoTime()

        return ProxyingPreparedStatement(
            sql,
            supplier(),
            startTimeNano,
            statsCollector
        )
    }
}
