import type { Metadata } from "next";
import "./globals.css";
import { Header, Footer } from "@/components";
import localFont from "next/font/local";

import styles from "./styles.module.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, ThemeConfig } from "antd";

const Axelix_Font = localFont({
  src: "../fonts/Variable_Golos_Text.woff2",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme: ThemeConfig = {
    token: {
      colorPrimary: "#00ab55",
      fontFamily: "Golos, Helvetica, Arial, sans-serif",
      fontSize: 15,
    },
  };

  return (
    <html lang="en">
      <body className={Axelix_Font.className}>
        <AntdRegistry>
          <ConfigProvider theme={theme}>
            <Header />
            <main className={styles.ContentLayout}>
              {children}
            </main>
            <Footer />
          </ConfigProvider>
        </AntdRegistry>
      </body >
    </html >
  );
}
