events {}

http {

    upstream website {
        server axelix-website:3000;
    }

    server {
        listen 80;
        server_name axelix.io;

        return 301 https://$host$request_uri;
    }

    server {

        listen 443 ssl;
        server_name axelix.io;

        ssl_certificate /etc/nginx/ssl/certificate.crt;
        ssl_certificate_key /etc/nginx/ssl/certificate.key;
        ssl_trusted_certificate /etc/nginx/ssl/certificate_ca.crt;

        location / {
            proxy_pass http://website;
            proxy_set_header Host $host; 
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /docs/ {
            # axelix-docs is supposed to resolve onto axelix-docs container within a docker network
            proxy_pass http://axelix-docs:3000;
            proxy_set_header Host $host;
        }

        location /blog/ {
            # axelix-docs is supposed to resolve onto axelix-docs container within a docker network
            proxy_pass http://axelix-docs:3000;
            proxy_set_header Host $host;
        }

        location ~ ^/(assets|img|__docusaurus)/ {
            proxy_pass http://axelix-docs:3000;
            proxy_set_header Host $host;
        }
    }
}