:ARP: https://en.wikipedia.org/wiki/Address_Resolution_Protocol[Address Resolution Protocol]

= Discovery Mechanism

This document outlines the motivations behind current discovery mechanism.

When the Axile Master as the Spring application bootstraps, it tries to determine the services that it is going to examine.
There are conceptually two different technical approaches that we can explore to make the Axile Master to know whether the given service is supposed to be managed by this Axile Master or not:

- Broadcasting
- Self-Registration

Let's explore both of them.

== Broadcasting Approach

In this approach, the Master is responsible to performing the  certain action that resembles the broadcast on the network (similar to what {ARP} does in routers for instance).

[#broadcast_architecture]
[plantuml]
....
@startuml
component [Spring Boot Service A]
component [Spring Boot Service B]
component [Go Service C]
component [Python Service D]
component [Python Service E]
component [Go Service F]

component [Axile Master]

[Axile Master] --> [Spring Boot Service A] : managed?
[Axile Master] --> [Spring Boot Service B] : managed?
[Axile Master] --> [Go Service C] : managed?
[Axile Master] --> [Python Service D] : managed?
[Axile Master] --> [Python Service E] : managed?
[Axile Master] --> [Go Service F] : managed?

@enduml
....

If we set aside the details of implementation of such an approach, we can immediately notice a couple of problems:

=== Problem 1. Scaling

The amount of the services that Axile Master handles would probably go up over time, as the new Spring Boot services are going to appear naturally inside an organization.

It is quite clear that the more services are out there, the more abstract broadcasting request are going to be sent over the network to the network entities that potentially do not represent the Spring Boot services.

So, this solution does not scale well.

=== Problem 2. Discovery

Assuming the app is deployed into K8S or any other orchestration tool, the Axile Master can employ Spring's `DiscoveryClient` to discover the services that are available. This is what the Spring Boot Admin does it for example. Similarly, the

However, this actually limits the service significantly, since it is based on the assumption that all the services that we're going to manage are discoverable by `DiscoveryClient`. It might easily be not the case.

It may be that the service aimed for being discovered is simply deployed outside K8S because of various reasons. Or the service might not be registered in Hashicorp Vault because of various reasons as well.

We need to aim for allowing the end-clients to plug-in Spring Boot services into the Axile management as seamlessly as we possibly can.

Therefore, this solution is a bit limited in terms of service discovery.

NOTE: We can employ multiple discovery services, or we can allow the users to extend the Axile Master here, but this already brings additional complication.

=== Problem 3. Conflicting Registration Resolution

Axile Master designed to be a single source of truth for Spring-based applications, and it is totally fine for a single Axile Master to handle all the Spring services in the organization. However, it is critical to understand that sometimes it is not always desirable or possible or even both, and we need to account for that.

Therefore, if the single service is going to be discoverable by multiple Axile Master instances, we would have to design a  negotiation protocol to allow the discoverable service to tell the broadcasting Axile Master instance that it is not going to register for it but for another Master.

== Self Registration

This approach assumes that the service that includes the Axile SBS and wants to be discovered should reach out to the Axile Master itself.

[#self_registartion_architecture]
[plantuml]
....
@startuml
component [Spring Boot Service A]
component [Spring Boot Service B]
component [Go Service C]
component [Python Service D]
component [Python Service E]
component [Go Service F]

component [Axile Master]

[Axile Master] <-- [Spring Boot Service A] : register me
[Axile Master] <-- [Spring Boot Service B] : register me
[Axile Master] -[hidden]-> [Go Service C]
[Axile Master] -[hidden]-> [Python Service D]
[Axile Master] -[hidden]-> [Python Service E]
[Axile Master] -[hidden]-> [Go Service F]

@enduml
....


Let's discuss how this approach addresses the issues above:

1. This solution is more scalable, since it does not depend on the amount of other non-Spring Boot network applications.
2. It is not limited to its discovery abilities, since it is the job of the discovered service to reach out to the Axile Master and not vice versa
3. The Axile SBS can be potentially configured to register itself with multiple Axile masters.

== Conclusion

Because of this, the decision was made from the architectural point of view for services themselves being responsible for being discovered.