apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      annotations:
        helm.sh/hook-time: {{ now | quote }}
      labels:
        app: front-end
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: {{ .Values.image.ref }}
          ports:
            - containerPort: 80