server:
  port: 8080

# TODO: we need to think about the design of properties in general
spring:
  application:
    name: axelix
  ai:
    mcp:
      server:
        protocol: streamable
        name: "axelix-mcp-server"
        streamable-http:
          mcp-endpoint: "/api/mcp"

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: [ "health" ]
axelix:
  master:
    discovery:
      auto: true
      platform: kubernetes
      kubernetes:
        kube-apiserver-url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}
        sa-token-path: /var/run/secrets/kubernetes.io/serviceaccount/token
        ca-cert-path: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        filters:
          namespaces: default
    auth:
      jwt:
        lifespan: 12h
      static-admin:
        credentials:
          password: admin
          username: admin
      type: static-admin
      cookie:
        name: auth_token
        secure: false
