openapi: 3.0.1
info:
  title: Nucleon Forge Axile
  version: 1.0.0

tags:
  - name: Loggers API Controller
    description: The loggers endpoint provides access to the application’s loggers and the configuration of their levels.

  - name: Wallboard API
    description: The endpoints related to wallboard grid rendering

  - name: Beans API
    description: The beans endpoint provides information about the application’s beans.

  - name: Configprops API Controller
    description: The configprops endpoint provides information about the application’s @ConfigurationProperties beans.

  - name: General instance information API
    description: The info endpoint provides general information about the particular Spring Boot instance

  - name: Property Management API
    description: Provides operations for managing Spring properties of application instances.

  - name: Environment API Controller
    description: The env endpoint provides information about the application’s Environment.

  - name: Profile Management API
    description: Provides operations for managing Spring profiles of application instances.

  - name: Caches API Controller
    description: The caches endpoint provides access to the application’s caches.

  - name: API for working with Users
    description: The beans endpoint provides information about the application’s beans.

paths:
######### Users API -> /response/user.yaml -> LoginRequest #########
  /users/login:
    post:
      tags:
        - API for working with Users
      summary: Log-in by the username/password combination
      operationId: login
      parameters:
        - name: loginRequest
          in: query
          description: Request for login
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: './response/user.yaml#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: OK
          headers:
            Authorization:
              description: The JWT token that should be subsequently used for auth purposes
              required: true
              style: simple
              schema:
                type: string
          content:
            '*/*':
              schema:
                type: object
        "400":
          $ref: "./response/error.yaml#/components/responses/BadRequest"
        "401":
          $ref: "./response/error.yaml#/components/responses/Unauthorized"
        "403":
          $ref: "./response/error.yaml#/components/responses/Forbidden"
        "500":
          $ref: "./response/error.yaml#/components/responses/InternalError"

######### Wallboard API -> /response/wallboard.yaml -> InstancesGridResponse #########
  /applications/grid:
    get:
      tags:
        - Wallboard API
      summary: Returns all instances that are managed by this Axile deployment
      operationId: getInstancesGrid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './response/wallboard.yaml#/components/schemas/InstancesGridResponse'
        "400":
          $ref: "./response/error.yaml#/components/responses/BadRequest"
        "500":
          $ref: "./response/error.yaml#/components/responses/InternalError"

######### Beans API -> /response/beans.yaml -> BeansFeedResponse #########
  /beans/feed/{instanceId}:
    get:
      tags:
        - Beans API
      summary: Returns beans feed for the given instance
      operationId: getBeansProfile
      parameters:
        - name: instanceId
          in: path
          description: Application Instance ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './response/beans.yaml#/components/schemas/BeansFeedResponse'
          links:
            Actuator/Beans:
              description: 'https://docs.spring.io/spring-boot/api/rest/actuator/beans.html'
        "400":
          $ref: "./response/error.yaml#/components/responses/BadRequest"
        "500":
          $ref: "./response/error.yaml#/components/responses/InternalError"

######### Environment API -> /response/environment.yaml -> EnvironmentFeedResponse #########
  /env/feed/{instanceId}:
    get:
      tags:
        - Environment API Controller
      summary: Returns information about the application’s Environment.
      operationId: getEnvironment
      parameters:
        - name: instanceId
          in: path
          description: Application Instance ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './response/environment.yaml#/components/schemas/EnvironmentFeedResponse'
          links:
            Spring Boot / Actuator / Environment (env):
              description: 'https://docs.spring.io/spring-boot/api/rest/actuator/env.html'
        "400":
          $ref: "./response/error.yaml#/components/responses/BadRequest"
        "500":
          $ref: "./response/error.yaml#/components/responses/InternalError"

######### Environment API -> /response/environment.yaml -> EnvironmentPropertyResponse #########
  /env/{instanceId}/property/{propertyName}:
    get:
      tags:
        - Environment API Controller
      summary: Returns a specific property of an instance
      operationId: getProperty
      parameters:
        - name: instanceId
          in: path
          description: Application Instance ID
          required: true
          schema:
            type: string
        - name: propertyName
          in: path
          description: Name of the environment property
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './response/environment.yaml#/components/schemas/EnvironmentPropertyResponse'
          links:
            Actuator/Environment(env):
              description: 'https://docs.spring.io/spring-boot/api/rest/actuator/env.html'
        "400":
          $ref: "./response/error.yaml#/components/responses/BadRequest"
        "500":
          $ref: "./response/error.yaml#/components/responses/InternalError"

######### Info API -> /response/info.yaml -> InfoResponse #########
  /info/{instanceId}:
    get:
      tags:
        - General instance information API
      summary: Returns general information about the instance.
      operationId: getInfoResponse
      parameters:
        - name: instanceId
          in: path
          description: Application Instance ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './response/info.yaml#/components/schemas/InfoResponse'
          links:
            Actuator/Info:
              description: 'https://docs.spring.io/spring-boot/api/rest/actuator/info.html'
        "400":
          $ref: "./response/error.yaml#/components/responses/BadRequest"
        "500":
          $ref: "./response/error.yaml#/components/responses/InternalError"

######### Software API -> /response/software.yaml -> InfoResponse #########
  /software/core/summary:
    get:
      tags:
        - software-api
      operationId: getCoreDistributionGrid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: './response/software.yaml#/components/schemas/DistributionSummaryResponse'