FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY .next/standalone ./
COPY .next/standalone/public ./public
COPY .next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]
