FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY .next/standalone ./
# COPY .next/standalone/public ./public
COPY .next/static ./.next/static

RUN adduser --system --uid 1000 nextjs
USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
