name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches: [feature/GH-799]
#    paths:
#      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci
        working-directory: website

      - name: Build
        run: npm run build
        working-directory: website

      - name: Copy global resources to VM via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.WEBSITE_PRODUCTION_VM_HOST }}
          username: ${{ secrets.WEBSITE_PRODUCTION_VM_USER }}
          key: ${{ secrets.WEBSITE_PRODUCTION_VM_PRIVATE_KEY }}
          source: "docker-compose.yml,infra/nginx"
          target: "/home/${{ secrets.WEBSITE_PRODUCTION_VM_USER }}"

      - name: Prepare Standalone Folder
        working-directory: website
        run: |
          cp -r public .next/standalone/
          cp -r .next/static .next/standalone/.next/

      - name: Copy build resources to VM via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.WEBSITE_PRODUCTION_VM_HOST }}
          username: ${{ secrets.WEBSITE_PRODUCTION_VM_USER }}
          key: ${{ secrets.WEBSITE_PRODUCTION_VM_PRIVATE_KEY }}
          source: "website/.next/static,website/.next/standalone,website/Dockerfile"
          target: "/home/${{ secrets.WEBSITE_PRODUCTION_VM_USER }}/axelix-website"
          strip_components: 1

      - name: Build Docker image on server and restart container
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.WEBSITE_PRODUCTION_VM_HOST }}
          username: ${{ secrets.WEBSITE_PRODUCTION_VM_USER }}
          key: ${{ secrets.WEBSITE_PRODUCTION_VM_PRIVATE_KEY }}
          script: |
            set -eux
            cd /home/${{ secrets.WEBSITE_PRODUCTION_VM_USER }}
            sudo docker compose up --build -d
