name: Deploy Website

on:
  push:
    branches: [feature/GH-778]
#    paths:
#      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci

      - name: Build
        run:  npm run build

      - name: Prepare Standalone Folder
        run: |
          cp -r public .next/standalone/
          cp -r .next/static .next/standalone/.next/

      - name: Copy build to VM via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.WEBSITE_PRODUCTION_VM_HOST }}
          username: ${{ secrets.WEBSITE_PRODUCTION_VM_USER }}
          key: ${{ secrets.WEBSITE_PRODUCTION_VM_PRIVATE_KEY }}
          source: "website/.next/static,website/.next/standalone,website/Dockerfile"
          target: "/home/${{ secrets.WEBSITE_PRODUCTION_VM_USER }}/axelix-website"
          strip_components: 1
    
      - name: Build Docker image on server and restart container
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.WEBSITE_PRODUCTION_VM_HOST }}
          username: ${{ secrets.WEBSITE_PRODUCTION_VM_USER }}
          key: ${{ secrets.WEBSITE_PRODUCTION_VM_PRIVATE_KEY }}
          script: |
            set -eux
            cd /home/${{ secrets.WEBSITE_PRODUCTION_VM_USER }}/axelix-website
            sudo docker compose down
            sudo docker compose up --build -d
